message("-- Configuring HDF5...")
#  message("-- In case you need it, set your HDF5_ROOT here:")
#  set(HDF5_ROOT "/your_local_path_to_hdf5_lib/")
if(DEFINED ENV{HDF5_ROOT})
  message("-- HDF5_ROOT properly set in environmental var:" $ENV{HDF5_ROOT})
elseif(DEFINED ENV{HDF5_DIR})
  message("-- HDF5_DIR properly set in environmental var:" $ENV{HDF5_DIR})
elseif(HDF5_ROOT)
  message("-- HDF5_ROOT properly set in cmake:" ${HDF5_ROOT})
else()
  message("-- POSSIBLE ERROR! Environmental variables HDF5_ROOT/HDF5_DIR not properly set!")
  message("-- If Cmake does not find HDF5 package you have two options:")
  message("--   1. Define environmental variables HDF5_ROOT and/or HDF5_DIR")
  message("--   2. In case you don't wnow ant/can't, define HDF5_ROOT in cmake/hdf5.cmake")
  message("-- If Cmake find HDF5 everything is Ok!")
endif()
set(HDF5_PREFER_PARALLEL TRUE)
find_package(HDF5 REQUIRED COMPONENTS Fortran C HL)
if (NOT HDF5_FOUND)
	#do nothing
	message(FATAL_ERROR "HDF5 not found!")
endif()

function(set_hdf5)
	include_directories(${HDF5_INCLUDE_DIRS})
	# If CMake version older than 3.20, use the following line
	if(${CMAKE_VERSION} VERSION_LESS "3.20.0")
		target_link_libraries(${PROJECT_NAME} hdf5 hdf5_hl hdf5_fortran hdf5_hl_fortran)
	else()
		target_link_libraries(${PROJECT_NAME} HDF5::HDF5)
	endif()
endfunction()
